const Anthropic = require("@anthropic-ai/sdk");

const BOT_TOKEN = process.env.BOT_TOKEN;
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;

const anthropic = new Anthropic({ apiKey: ANTHROPIC_API_KEY });

const users = {};

function getUser(id) {
  if (!users[id]) {
    users[id] = {
      id,
      isPro: false,
      proExpiry: null,
      streak: 0,
      lastSession: null,
      sessions: 0,
      lang: null,
      joinedAt: new Date().toISOString(),
    };
  }
  return users[id];
}

function isProActive(user) {
  if (!user.isPro || !user.proExpiry) return false;
  return new Date(user.proExpiry) > new Date();
}

function updateStreak(user) {
  const now = new Date();
  const last = user.lastSession ? new Date(user.lastSession) : null;
  if (!last) {
    user.streak = 1;
  } else {
    const diffDays = Math.floor((now - last) / (1000 * 60 * 60 * 24));
    if (diffDays === 1) user.streak += 1;
    else if (diffDays > 1) user.streak = 1;
  }
  user.lastSession = new Date().toISOString();
  user.sessions += 1;
}

// ---------------------------------------------------------------------------
// Translations
// ---------------------------------------------------------------------------
const T = {
  en: {
    welcome: (name) => `🧘 <b>Welcome to Asanai, ${name}!</b>\n\nYour AI-powered yoga and wellness companion — right here in Telegram.\n\n✨ Get personalized yoga plans generated by AI\n📚 Access guided classes anytime\n🔥 Build your daily streak\n⭐ Upgrade to Pro for unlimited access\n\nWhat would you like to do today?`,
    chooseGoal: "🧘 <b>What do you need today?</b>\n\nChoose your goal and I'll generate a personalized yoga plan for you:",
    generating: "✨ <i>Generating your personalized plan...</i>",
    error: "Something went wrong generating your plan. Please try again.",
    classesTextFree: "📚 <b>Classes</b>\n\nFree classes are open. Upgrade to Pro to unlock everything.",
    classesTextPro: "📚 <b>All classes</b>\n\nAll sessions unlocked. Enjoy your practice!",
    classLocked: "🔒 <b>Pro class</b>\n\nThis class is available to Pro members. Upgrade to unlock unlimited classes, AI plans, and full programs.",
    sessionDone: (streak, sessions) => `🎉 <b>Session complete!</b>\n\nGreat work. Your body thanks you.\n\n🔥 Streak: <b>${streak} days</b>\n📊 Total sessions: <b>${sessions}</b>`,
    streakMsg: (user, pro) => {
      const s = user.streak;
      const msg = s >= 7 ? `🏆 <b>${s}-day streak!</b> You're on fire.` : s >= 3 ? `🔥 <b>${s}-day streak!</b> Keep it going!` : s === 1 ? `🌱 <b>1-day streak.</b> Great start — come back tomorrow!` : `💪 Start your streak today — complete any session!`;
      return `📊 <b>Your progress</b>\n\n${msg}\n\n📅 Total sessions: <b>${user.sessions}</b>\n⭐ Plan: <b>${pro ? "Pro" : "Free"}</b>`;
    },
    upgradeText: "⭐ <b>Asanai Pro</b>\n\nUnlock everything:\n\n✅ Unlimited AI yoga plans\n✅ All classes + new ones weekly\n✅ Full 30-day programs\n✅ Progress reports\n✅ Priority AI coaching\n\nCancel anytime.",
    proActive: (date) => `⭐ <b>Pro active</b>\n\nYour membership is active until <b>${date}</b>.\n\nEnjoy unlimited access!`,
    paymentSuccess: (date) => `🎉 <b>Welcome to Asanai Pro!</b>\n\nYour weekly membership is now active.\n\n✅ All classes unlocked\n✅ Unlimited AI plans\n✅ Full programs available\n\nValid until <b>${date}</b>.\n\nLet's practice! 🧘`,
    differentGoal: "🔄 Different goal",
    home: "← Home",
    back: "← Back",
    allClasses: "← All classes",
    startSession: "✅ Mark as done",
    startNewSession: "🧘 Start a session",
    upgradeBtn: "⭐ Upgrade to Pro",
    subscribeBtn: "⭐ Subscribe — 299 Stars/week",
    getMyPlan: "🧘 Get my yoga plan",
    classes: "📚 Classes",
    myStreak: "🔥 My streak",
    goPro: "⭐ Go Pro",
    proActiveBtn: "⭐ Pro active",
    goals: {
      relax: "😌 Stretch & relax",
      energize: "⚡ Energize",
      backpain: "🦴 Back pain relief",
      sleep: "🌙 Better sleep",
      core: "💪 Core strength",
      flexible: "🤸 Flexibility",
    },
    langBtn: "🌐 Language / Idioma",
    changeLang: "Choose your language:",
    planLabel: "Your plan",
    streakLabel: (s, sess) => `\n\n🔥 Streak: <b>${s} days</b> · Sessions: <b>${sess}</b>`,
  },
  es: {
    welcome: (name) => `🧘 <b>¡Bienvenido a Asanai, ${name}!</b>\n\nTu compañero de yoga e bienestar con IA — aquí mismo en Telegram.\n\n✨ Planes de yoga personalizados generados por IA\n📚 Clases guiadas cuando quieras\n🔥 Construye tu racha diaria\n⭐ Mejora a Pro para acceso ilimitado\n\n¿Qué te gustaría hacer hoy?`,
    chooseGoal: "🧘 <b>¿Qué necesitas hoy?</b>\n\nElige tu objetivo y generaré un plan de yoga personalizado para ti:",
    generating: "✨ <i>Generando tu plan personalizado...</i>",
    error: "Algo salió mal al generar tu plan. Por favor intenta de nuevo.",
    classesTextFree: "📚 <b>Clases</b>\n\nLas clases gratuitas están disponibles. Mejora a Pro para desbloquear todo.",
    classesTextPro: "📚 <b>Todas las clases</b>\n\n¡Todas las sesiones desbloqueadas. Disfruta tu práctica!",
    classLocked: "🔒 <b>Clase Pro</b>\n\nEsta clase está disponible para miembros Pro. Mejora para desbloquear clases ilimitadas, planes de IA y programas completos.",
    sessionDone: (streak, sessions) => `🎉 <b>¡Sesión completada!</b>\n\nExcelente trabajo. Tu cuerpo te lo agradece.\n\n🔥 Racha: <b>${streak} días</b>\n📊 Sesiones totales: <b>${sessions}</b>`,
    streakMsg: (user, pro) => {
      const s = user.streak;
      const msg = s >= 7 ? `🏆 <b>¡Racha de ${s} días!</b> ¡Estás en llamas!` : s >= 3 ? `🔥 <b>¡Racha de ${s} días!</b> ¡Sigue así!` : s === 1 ? `🌱 <b>Racha de 1 día.</b> ¡Buen inicio — vuelve mañana!` : `💪 ¡Comienza tu racha hoy — completa cualquier sesión!`;
      return `📊 <b>Tu progreso</b>\n\n${msg}\n\n📅 Sesiones totales: <b>${user.sessions}</b>\n⭐ Plan: <b>${pro ? "Pro" : "Gratis"}</b>`;
    },
    upgradeText: "⭐ <b>Asanai Pro</b>\n\nDesbloquea todo:\n\n✅ Planes de yoga ilimitados con IA\n✅ Todas las clases + nuevas cada semana\n✅ Programas completos de 30 días\n✅ Reportes de progreso\n✅ Coaching IA prioritario\n\nCancela cuando quieras.",
    proActive: (date) => `⭐ <b>Pro activo</b>\n\nTu membresía está activa hasta <b>${date}</b>.\n\n¡Disfruta acceso ilimitado!`,
    paymentSuccess: (date) => `🎉 <b>¡Bienvenido a Asanai Pro!</b>\n\nTu membresía semanal está activa.\n\n✅ Todas las clases desbloqueadas\n✅ Planes IA ilimitados\n✅ Programas completos disponibles\n\nVálido hasta <b>${date}</b>.\n\n¡A practicar! 🧘`,
    differentGoal: "🔄 Otro objetivo",
    home: "← Inicio",
    back: "← Atrás",
    allClasses: "← Todas las clases",
    startSession: "✅ Marcar como hecho",
    startNewSession: "🧘 Iniciar una sesión",
    upgradeBtn: "⭐ Mejorar a Pro",
    subscribeBtn: "⭐ Suscribirse — 299 Stars/semana",
    getMyPlan: "🧘 Mi plan de yoga",
    classes: "📚 Clases",
    myStreak: "🔥 Mi racha",
    goPro: "⭐ Ir a Pro",
    proActiveBtn: "⭐ Pro activo",
    goals: {
      relax: "😌 Estirar y relajar",
      energize: "⚡ Energizarme",
      backpain: "🦴 Dolor de espalda",
      sleep: "🌙 Dormir mejor",
      core: "💪 Fuerza de núcleo",
      flexible: "🤸 Flexibilidad",
    },
    langBtn: "🌐 Language / Idioma",
    changeLang: "Elige tu idioma:",
    planLabel: "Tu plan",
    streakLabel: (s, sess) => `\n\n🔥 Racha: <b>${s} días</b> · Sesiones: <b>${sess}</b>`,
  },
};

function t(user) {
  return T[user.lang || "en"];
}

// ---------------------------------------------------------------------------
// Telegram API helpers
// ---------------------------------------------------------------------------
async function callTelegram(method, body) {
  const res = await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/${method}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  return res.json();
}

async function sendMessage(chatId, text, extra = {}) {
  return callTelegram("sendMessage", { chat_id: chatId, text, parse_mode: "HTML", ...extra });
}

// ---------------------------------------------------------------------------
// Keyboards
// ---------------------------------------------------------------------------
function mainMenu(user) {
  const tx = t(user);
  const pro = isProActive(user);
  return {
    inline_keyboard: [
      [{ text: tx.getMyPlan, callback_data: "menu_plan" }, { text: tx.classes, callback_data: "menu_classes" }],
      [{ text: tx.myStreak, callback_data: "menu_streak" }, { text: pro ? tx.proActiveBtn : tx.goPro, callback_data: pro ? "menu_profile" : "menu_upgrade" }],
      [{ text: tx.langBtn, callback_data: "menu_lang" }],
    ],
  };
}

function goalMenu(user) {
  const tx = t(user);
  return {
    inline_keyboard: [
      [{ text: tx.goals.relax, callback_data: "plan_relax" }, { text: tx.goals.energize, callback_data: "plan_energize" }],
      [{ text: tx.goals.backpain, callback_data: "plan_backpain" }, { text: tx.goals.sleep, callback_data: "plan_sleep" }],
      [{ text: tx.goals.core, callback_data: "plan_core" }, { text: tx.goals.flexible, callback_data: "plan_flexible" }],
      [{ text: tx.back, callback_data: "back_main" }],
    ],
  };
}

function classesMenu(user) {
  const pro = isProActive(user);
  const tx = t(user);
  const lock = pro ? "" : " 🔒";
  return {
    inline_keyboard: [
      [{ text: "☀️ Sun Salutation — 25 min", callback_data: "class_sun" }],
      [{ text: "🧠 Guided Meditation — 15 min", callback_data: "class_med" }],
      [{ text: "💨 Pranayama Breathing — 20 min", callback_data: "class_breath" }],
      [{ text: `🔥 Power Vinyasa — 45 min${lock}`, callback_data: pro ? "class_vinyasa" : "class_locked" }],
      [{ text: `🌙 Sleep Yoga Nidra — 30 min${lock}`, callback_data: pro ? "class_nidra" : "class_locked" }],
      [{ text: `❤️ Yin & Restore — 60 min${lock}`, callback_data: pro ? "class_yin" : "class_locked" }],
      [{ text: tx.back, callback_data: "back_main" }],
    ],
  };
}

function langMenu() {
  return {
    inline_keyboard: [
      [{ text: "🇺🇸 English", callback_data: "lang_en" }, { text: "🇪🇸 Español", callback_data: "lang_es" }],
    ],
  };
}

// ---------------------------------------------------------------------------
// Class content (bilingual)
// ---------------------------------------------------------------------------
function getClassInfo(key, lang) {
  const classes = {
    en: {
      class_sun: { title: "☀️ Sun Salutation Flow", body: `<b>25 min · Beginner · Free</b>\n\nA classic energizing sequence linking breath with movement.\n\n<b>What you'll do:</b>\nMountain pose → Forward fold → Plank → Cobra → Downward dog → Warrior I\n\n💡 <i>Move slowly at first, let your breath lead.</i>` },
      class_med: { title: "🧠 Guided Meditation", body: `<b>15 min · All levels · Free</b>\n\nA calming body-scan meditation to quiet the mind.\n\n<b>What you'll do:</b>\nBreath awareness → Body scan → Visualization → Return to presence\n\n💡 <i>Let thoughts pass like clouds.</i>` },
      class_breath: { title: "💨 Pranayama Breathing", body: `<b>20 min · Beginner · Free</b>\n\nFoundational yoga breathing techniques.\n\n<b>What you'll do:</b>\nNadi Shodhana → Ujjayi breath → Box breathing → Kapalabhati\n\n💡 <i>Never force the breath.</i>` },
      class_vinyasa: { title: "🔥 Power Vinyasa", body: `<b>45 min · Intermediate · Pro</b>\n\nA dynamic heat-building flow.\n\n<b>What you'll do:</b>\nWarm-up → Standing sequence → Arm balances → Core → Cool down\n\n💡 <i>Modify any pose — your edge is perfect.</i>` },
      class_nidra: { title: "🌙 Sleep Yoga Nidra", body: `<b>30 min · All levels · Pro</b>\n\nGuided sleep-based meditation — deeply restorative.\n\n<b>What you'll do:</b>\nBody scan → Breath awareness → Visualization → Deep rest\n\n💡 <i>Let yourself fall asleep — that's the goal.</i>` },
      class_yin: { title: "❤️ Yin & Restore", body: `<b>60 min · All levels · Pro</b>\n\nLong-held passive poses targeting deep connective tissue.\n\n<b>What you'll do:</b>\nButterfly → Dragon → Sleeping swan → Spinal twist → Savasana\n\n💡 <i>Hold each pose 3–5 min. Surrender.</i>` },
    },
    es: {
      class_sun: { title: "☀️ Flujo de Saludos al Sol", body: `<b>25 min · Principiante · Gratis</b>\n\nUna secuencia clásica que une respiración y movimiento.\n\n<b>Qué harás:</b>\nPostura montaña → Flexión → Plancha → Cobra → Perro boca abajo → Guerrero I\n\n💡 <i>Muévete despacio, deja que tu respiración guíe.</i>` },
      class_med: { title: "🧠 Meditación Guiada", body: `<b>15 min · Todos los niveles · Gratis</b>\n\nMeditación de escaneo corporal para calmar la mente.\n\n<b>Qué harás:</b>\nConciencia de respiración → Escaneo corporal → Visualización\n\n💡 <i>Deja que los pensamientos pasen como nubes.</i>` },
      class_breath: { title: "💨 Respiración Pranayama", body: `<b>20 min · Principiante · Gratis</b>\n\nTécnicas fundamentales de respiración del yoga.\n\n<b>Qué harás:</b>\nNadi Shodhana → Respiración Ujjayi → Respiración cuadrada → Kapalabhati\n\n💡 <i>Nunca fuerces la respiración.</i>` },
      class_vinyasa: { title: "🔥 Vinyasa de Poder", body: `<b>45 min · Intermedio · Pro</b>\n\nFlujo dinámico que genera calor y energía.\n\n<b>Qué harás:</b>\nCalentamiento → Secuencia de pie → Equilibrios → Núcleo → Enfriamiento\n\n💡 <i>Modifica cualquier postura — tu límite es perfecto.</i>` },
      class_nidra: { title: "🌙 Yoga Nidra para Dormir", body: `<b>30 min · Todos los niveles · Pro</b>\n\nMeditación guiada basada en el sueño — profundamente restauradora.\n\n<b>Qué harás:</b>\nEscaneo corporal → Conciencia de respiración → Visualización → Descanso profundo\n\n💡 <i>Déjate quedar dormido — ese es el objetivo.</i>` },
      class_yin: { title: "❤️ Yin y Restauración", body: `<b>60 min · Todos los niveles · Pro</b>\n\nPosturas pasivas largas que trabajan el tejido conectivo profundo.\n\n<b>Qué harás:</b>\nMariposa → Dragón → Cisne durmiente → Torsión espinal → Savasana\n\n💡 <i>Mantén cada postura 3–5 min. Ríndete.</i>` },
    },
  };
  return classes[lang || "en"][key];
}

// ---------------------------------------------------------------------------
// AI yoga plan
// ---------------------------------------------------------------------------
async function generateYogaPlan(goal, lang) {
  const goals = {
    relax: { en: "gentle stretching and relaxation, releasing tension", es: "estiramiento suave y relajación, liberando tensión" },
    energize: { en: "energizing morning flow with dynamic sun salutations", es: "flujo matutino energizante con saludos al sol dinámicos" },
    backpain: { en: "lower back pain relief and core strengthening", es: "alivio del dolor de espalda baja y fortalecimiento del núcleo" },
    sleep: { en: "bedtime wind-down with calming breathwork", es: "relajación nocturna con respiración calmante" },
    core: { en: "core strength and stability building", es: "construcción de fuerza y estabilidad del núcleo" },
    flexible: { en: "deep flexibility and hip opening", es: "flexibilidad profunda y apertura de caderas" },
  };

  const focus = goals[goal]?.[lang] || goals.relax.en;
  const isEs = lang === "es";

  const prompt = isEs
    ? `Eres Asanai, un coach de yoga con IA. Crea un plan de sesión de yoga corto y amigable para alguien que quiere: ${focus}. Nivel: principiante.

Responde en este formato exacto:
TITULO: [nombre de la sesión]
DURACION: [X min]
DESCRIPCION: [máximo 2 oraciones, cálidas y motivadoras]
POSTURAS:
1. [Nombre de postura] — [duración] — [beneficio en una línea]
2. [Nombre de postura] — [duración] — [beneficio en una línea]
3. [Nombre de postura] — [duración] — [beneficio en una línea]
4. [Nombre de postura] — [duración] — [beneficio en una línea]
5. [Nombre de postura] — [duración] — [beneficio en una línea]
CONSEJO: [un consejo práctico para la sesión de hoy]

Mantén un tono cálido, alentador y simple. Sin markdown, solo texto plano.`
    : `You are Asanai, an AI yoga coach. Create a short friendly yoga session plan for someone who wants: ${focus}. Level: beginner.

Respond in this exact format:
TITLE: [session name]
DURATION: [X min]
DESCRIPTION: [2 sentences max, warm and motivating]
POSES:
1. [Pose name] — [duration] — [one-line benefit]
2. [Pose name] — [duration] — [one-line benefit]
3. [Pose name] — [duration] — [one-line benefit]
4. [Pose name] — [duration] — [one-line benefit]
5. [Pose name] — [duration] — [one-line benefit]
TIP: [one practical tip for today's session]

Keep it warm, encouraging, and simple. No markdown, just plain text.`;

  const msg = await anthropic.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 1000,
    messages: [{ role: "user", content: prompt }],
  });

  return msg.content[0].text;
}

function formatPlan(raw, lang) {
  const isEs = lang === "es";
  const lines = raw.split("\n").filter((l) => l.trim());
  let out = isEs ? "🧘 <b>Tu Sesión Asanai</b>\n\n" : "🧘 <b>Your Asanai Session</b>\n\n";

  for (const line of lines) {
    const key = isEs ? ["TITULO:", "DURACION:", "DESCRIPCION:", "POSTURAS:", "CONSEJO:"] : ["TITLE:", "DURATION:", "DESCRIPTION:", "POSES:", "TIP:"];
    if (line.startsWith(key[0])) out += `<b>${line.replace(key[0], "").trim()}</b>\n`;
    else if (line.startsWith(key[1])) out += `⏱ ${line.replace(key[1], "").trim()}\n\n`;
    else if (line.startsWith(key[2])) out += `${line.replace(key[2], "").trim()}\n\n`;
    else if (line.startsWith(key[3])) out += `<b>${isEs ? "Tus posturas:" : "Your poses:"}</b>\n`;
    else if (/^\d\./.test(line)) out += `${line}\n`;
    else if (line.startsWith(key[4])) out += `\n💡 <i>${line.replace(key[4], "").trim()}</i>`;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------
async function handleStart(chatId, firstName) {
  const user = getUser(chatId);
  const name = firstName || "friend";

  if (!user.lang) {
    await sendMessage(chatId, `🌐 Welcome to Asanai!\n\nBienvenido a Asanai!\n\nChoose your language / Elige tu idioma:`, { reply_markup: langMenu() });
    return;
  }

  await sendMessage(chatId, t(user).welcome(name), { reply_markup: mainMenu(user) });
}

async function handleCallback(query) {
  const chatId = query.message.chat.id;
  const msgId = query.message.message_id;
  const data = query.data;
  const user = getUser(chatId);
  const pro = isProActive(user);
  const tx = t(user);

  await callTelegram("answerCallbackQuery", { callback_query_id: query.id });

  // Language selection
  if (data === "menu_lang") {
    await callTelegram("editMessageText", { chat_id: chatId, message_id: msgId, text: tx.changeLang, parse_mode: "HTML", reply_markup: langMenu() });
    return;
  }

  if (data === "lang_en" || data === "lang_es") {
    user.lang = data === "lang_en" ? "en" : "es";
    const firstName = query.from?.first_name || "friend";
    await callTelegram("editMessageText", { chat_id: chatId, message_id: msgId, text: t(user).welcome(firstName), parse_mode: "HTML", reply_markup: mainMenu(user) });
    return;
  }

  if (data === "back_main") {
    await callTelegram("editMessageText", { chat_id: chatId, message_id: msgId, text: user.lang === "es" ? "¿Qué te gustaría hacer hoy?" : "What would you like to do today?", parse_mode: "HTML", reply_markup: mainMenu(user) });
    return;
  }

  if (data === "menu_plan") {
    await callTelegram("editMessageText", { chat_id: chatId, message_id: msgId, text: tx.chooseGoal, parse_mode: "HTML", reply_markup: goalMenu(user) });
    return;
  }

  if (data.startsWith("plan_")) {
    const goal = data.replace("plan_", "");
    await callTelegram("editMessageText", { chat_id: chatId, message_id: msgId, text: tx.generating, parse_mode: "HTML" });
    try {
      const raw = await generateYogaPlan(goal, user.lang);
      const formatted = formatPlan(raw, user.lang);
      updateStreak(user);
      await callTelegram("editMessageText", {
        chat_id: chatId, message_id: msgId,
        text: formatted + tx.streakLabel(user.streak, user.sessions),
        parse_mode: "HTML",
        reply_markup: { inline_keyboard: [[{ text: tx.differentGoal, callback_data: "menu_plan" }], [{ text: tx.home, callback_data: "back_main" }]] },
      });
    } catch (err) {
      await callTelegram("editMessageText", { chat_id: chatId, message_id: msgId, text: tx.error, parse_mode: "HTML", reply_markup: { inline_keyboard: [[{ text: tx.back, callback_data: "menu_plan" }]] } });
    }
    return;
  }

  if (data === "menu_classes") {
    await callTelegram("editMessageText", { chat_id: chatId, message_id: msgId, text: pro ? tx.classesTextPro : tx.classesTextFree, parse_mode: "HTML", reply_markup: classesMenu(user) });
    return;
  }

  if (data.startsWith("class_") && data !== "class_locked") {
    const info = getClassInfo(data, user.lang);
    if (info) {
      await callTelegram("editMessageText", {
        chat_id: chatId, message_id: msgId,
        text: `<b>${info.title}</b>\n\n${info.body}`,
        parse_mode: "HTML",
        reply_markup: { inline_keyboard: [[{ text: tx.startSession, callback_data: "class_done" }], [{ text: tx.allClasses, callback_data: "menu_classes" }]] },
      });
    }
    return;
  }

  if (data === "class_done") {
    updateStreak(user);
    await callTelegram("editMessageText", { chat_id: chatId, message_id: msgId, text: tx.sessionDone(user.streak, user.sessions), parse_mode: "HTML", reply_markup: { inline_keyboard: [[{ text: tx.home, callback_data: "back_main" }]] } });
    return;
  }

  if (data === "class_locked") {
    await callTelegram("editMessageText", {
      chat_id: chatId, message_id: msgId,
      text: tx.classLocked, parse_mode: "HTML",
      reply_markup: { inline_keyboard: [[{ text: tx.upgradeBtn, callback_data: "menu_upgrade" }], [{ text: tx.allClasses, callback_data: "menu_classes" }]] },
    });
    return;
  }

  if (data === "menu_streak") {
    await callTelegram("editMessageText", {
      chat_id: chatId, message_id: msgId,
      text: tx.streakMsg(user, pro), parse_mode: "HTML",
      reply_markup: { inline_keyboard: [[{ text: tx.startNewSession, callback_data: "menu_plan" }], [{ text: tx.home, callback_data: "back_main" }]] },
    });
    return;
  }

  if (data === "menu_upgrade") {
    await callTelegram("editMessageText", { chat_id: chatId, message_id: msgId, text: tx.upgradeText, parse_mode: "HTML", reply_markup: { inline_keyboard: [[{ text: tx.subscribeBtn, callback_data: "do_upgrade" }], [{ text: tx.back, callback_data: "back_main" }]] } });
    return;
  }

  if (data === "do_upgrade") {
    await callTelegram("sendInvoice", {
      chat_id: chatId, title: "Asanai Pro", description: user.lang === "es" ? "Clases ilimitadas + coaching IA. Cancela cuando quieras." : "Unlimited classes + AI coaching. Cancel anytime.",
      payload: "pro_weekly", currency: "XTR",
      prices: [{ label: user.lang === "es" ? "Membresía semanal Pro" : "Pro weekly membership", amount: 299 }],
    });
    return;
  }

  if (data === "menu_profile") {
    await callTelegram("editMessageText", { chat_id: chatId, message_id: msgId, text: tx.proActive(new Date(user.proExpiry).toLocaleDateString()), parse_mode: "HTML", reply_markup: { inline_keyboard: [[{ text: tx.home, callback_data: "back_main" }]] } });
    return;
  }
}

async function handlePayment(msg) {
  const chatId = msg.chat.id;
  const user = getUser(chatId);
  user.isPro = true;
  user.proExpiry = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
  await sendMessage(chatId, t(user).paymentSuccess(new Date(user.proExpiry).toLocaleDateString()), { reply_markup: mainMenu(user) });
}

// ---------------------------------------------------------------------------
// Vercel handler
// ---------------------------------------------------------------------------
module.exports = async function handler(req, res) {
  if (req.method === "GET") return res.status(200).json({ ok: true, app: "Asanai", status: "running" });
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  try {
    const update = req.body;

    if (update.message) {
      const msg = update.message;
      const chatId = msg.chat.id;
      const text = msg.text || "";
      const firstName = msg.from?.first_name;
      const user = getUser(chatId);

      if (msg.successful_payment) {
        await handlePayment(msg);
      } else if (text === "/start") {
        await handleStart(chatId, firstName);
      } else if (text === "/lang") {
        await sendMessage(chatId, t(user).changeLang, { reply_markup: langMenu() });
      } else if (text === "/plan") {
        await sendMessage(chatId, t(user).chooseGoal, { reply_markup: goalMenu(user) });
      } else if (text === "/classes") {
        await sendMessage(chatId, isProActive(user) ? t(user).classesTextPro : t(user).classesTextFree, { reply_markup: classesMenu(user) });
      } else if (text === "/streak") {
        await sendMessage(chatId, t(user).streakMsg(user, isProActive(user)));
      } else if (text === "/upgrade") {
        await sendMessage(chatId, t(user).upgradeText, { reply_markup: { inline_keyboard: [[{ text: t(user).subscribeBtn, callback_data: "do_upgrade" }]] } });
      } else if (text === "/help") {
        await sendMessage(chatId, user.lang === "es"
          ? `/start — menú principal\n/plan — obtener plan de yoga\n/classes — explorar clases\n/streak — ver tu progreso\n/upgrade — ir a Pro\n/lang — cambiar idioma`
          : `/start — main menu\n/plan — get a yoga plan\n/classes — browse classes\n/streak — see progress\n/upgrade — go Pro\n/lang — change language`);
      } else {
        await handleStart(chatId, firstName);
      }
    }

    if (update.callback_query) await handleCallback(update.callback_query);
    if (update.pre_checkout_query) await callTelegram("answerPreCheckoutQuery", { pre_checkout_query_id: update.pre_checkout_query.id, ok: true });

    res.status(200).json({ ok: true });
  } catch (err) {
    console.error("Webhook error:", err);
    res.status(200).json({ ok: true });
  }
};
